# Agent配置文件
# 每个section代表一个Agent实例，包含完整的Agent配置信息
[easy-accounts-agent]
id = 2
enable = true
name = easy-accounts
llm_use = easy-accounts
llm_think_use = easy-accounts
summary_llm_use = easy-accounts
enable_summary = false
enable_auto_question = false
enable_thinking = false
role = 小易.role
llm_memory_window = 10
tool_round = 8
tool_tokens = []
mcp_servers = []
mcp_tool_black_list = []
description = 一个家庭小财务官，擅长处理家庭财务账单相关问题
agent_list = []
# 内部工具列表
inner_tools = ["accounts", "types", "current_date", "year_statistics", "flows", "get_flow", "add_flow", "update_flow", "make_excel"]
# 任务指导文件列表（先加载inner内部指导，再加载用户映射的外部指导）
task_instructions_file = ["easy_accounts_instructions_inner.prompt", "easy_accounts_instructions.prompt"]
